$hash_calc_ignore_pattern{'eps'} = '^%%CreationDate: |^  \/CreationDate ';
$pdflatex='pdflatex -output-format pdf -shell-escape %O %S';
$latex='latex %O -shell-escape %S';
$dvipdf='xdvipdfmx %O -o %D %S';
